[server]
port = "8080"
read_timeout = "30s"
write_timeout = "30s"
max_header_bytes = 1048576

[log]
level = "info"
format = "json"
output = "stdout"

[database.mysql]
host = "localhost"
port = 3306
name = "demo"
user = "root"
password = "mysql"

[database.postgres]
host = "localhost"
port = 5432
name = "demo"
user = "postgres"
password = "postgresql"
